1. Create a 3x3 array that contains a diagonal of nines.


In [1]:
import numpy as np

In [2]:
diagonal=[9,9,9]
array = np.diag(diagonal)
print(array)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive)<br>
and use boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.

In [5]:
arr=np.arange(2,33,2).reshape(4,4)
print(arr)
mean_val=np.mean(arr)
std_val=np.std(arr)
print("===================\n Selected Values : \n")
print(arr[ (arr>mean_val-std_val/2) & (arr<mean_val+std_val/2)])

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
 Selected Values : 

[14 16 18 20]


3. Create a 9x9 array that contains only zeros of type int.


In [7]:
arr = np.zeros((9,9), dtype=int)
arr

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc...

In [8]:
while True:
    try:
        n=int(input("Enter a number: "))
        a=np.ones((n,n))
        b=np.arange(1,n+1)
        c=a*b
        print(c)
        break
    except ValueError:
        print("Enter a valid number")
    except KeyboardInterrupt:
        print("Keyboard Interrupt")
        exit()

Enter a number: 9
[[1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]]
